name: flutter_biblioteca_app
description: Aplicación de gestión de préstamos de libros en Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  printing: ^5.11.0
  
  http: ^0.13.5           # Para peticiones al backend PHP
  flutter_dotenv: ^5.0.2  # Para gestionar variables de entorno
  provider: ^6.1.1        # Para control de estado (opcional)
  shared_preferences: ^2.5.3
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
